### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Akharote1** [Akharote1/RazorIDE#1]
- [ ] Finish Resource Manager.
- [ ] Add USB Debugging support.
- [ ] Add all remaining documentations.
- [ ] Fix a few bugs and errors.
- [ ] Add an option to import .modpkg mods.
- [ ] Libraries!

If you have any more suggestions, comment them here or create a new issue and I will add it to the list.

**Comment by SaloEater** [comment]
If my language knowledge enough high, live code meaning intellisense? Or no?
Documention takes long time to check args.

**Comment by SirGamer** [comment]
Locking conversation as this is just a to-do list.

**Comment by Akharote1** [comment]
@SaloEater By live code interpreting, I mean where it points syntax errors. Kind of like how IntelliJ does. It doesn't take a long time on my computer. What are your computer specs?

@SirGamer Don't lock this issue. I want people to post suggestions here :P

**Comment by SirGamer** [comment]
Oh, okay. :P
